algolia/autocomplete

- .eslintrc
- README.md
- package.json
- src/autocomplete/dataset.js
- src/autocomplete/dropdown.js
- src/autocomplete/event_bus.js
- src/autocomplete/input.js
- src/autocomplete/plugin.js
- src/autocomplete/typeahead.js
- src/common/utils.js
```sh
> cat dist/autocomplete.jquery.min.js | gzip -9 | wc -c | pretty-bytes
17.05 kB
```
> chore: use lodash(compat) where relevant

- .eslintrc
- .travis.yml
- README.md
- package.json
- src/autocomplete/css.js
- src/autocomplete/dataset.js
- src/autocomplete/dropdown.js
- src/autocomplete/event_bus.js
- src/autocomplete/event_emitter.js
- src/autocomplete/input.js
- src/autocomplete/typeahead.js
- src/common/utils.js
- src/jquery/plugin.js
- test/fixtures.js
- test/helpers/waits_for.js
- test/integration/test.js
- test/unit/angular_spec.js
- test/unit/dataset_spec.js
- test/unit/dropdown_spec.js
- test/unit/event_emitter_spec.js
- test/unit/input_spec.js
- test/unit/jquery_spec.js
- test/unit/typeahead_spec.js
+ local grunt-cli (reduce project kickstart)
+ fixed eslint errors
+ added lint task in test
+ added jsfmt tool, checkstyle in test
> chore: local grunt-cli, fix eslint errors, add jsfmt

- src/sources/popularIn.js
source(first) result was not good
> fix(popularIn)

- README.md
- src/autocomplete/typeahead.js
- test/unit/typeahead_spec.js
> Emit a new 'updated' event as soon as one dataset is rendered.

- README.md
- src/angular/directive.js
- src/autocomplete/css.js
- src/autocomplete/dataset.js
- src/autocomplete/dropdown.js
- src/autocomplete/html.js
- src/autocomplete/typeahead.js
- src/common/utils.js
- src/jquery/plugin.js
- src/standalone/index.js
- test/unit/typeahead_spec.js
> Ability to customize underlying CSS classes

- src/angular/directive.js
- src/autocomplete/event_bus.js
- src/autocomplete/typeahead.js
- src/jquery/plugin.js
- src/standalone/index.js
> Issue allow select handler to prevent menu from being closed

- src/angular/directive.js
- src/autocomplete/typeahead.js
- src/jquery/plugin.js
- src/standalone/index.js
@redox hopefully this is fine, if I missed anything let me know will be happy to add/change.
> #113 autoselectOnBlur

- src/standalone/index.js
- test/unit/standalone_spec.js
> feat(noConflict): new method to avoid window conflict

- CHANGELOG.md
- README.md
- package.json
- release.sh
- yarn.lock
This automate the release process along
with generating a changelog and ensuring
semver consistency,
> chore(build): add full release process

- README.md
**Summary**
Just a few small fixes :)
> chore(README): whitespace and copy fixes

- src/sources/hits.js
- src/sources/popularIn.js
- test/playground.html
> fix(UA): add failsafe if params not provided

- README.md
**Summary**
Fixed syntax error in an example on the readme
> Fixed syntax error in an example

- scripts/netlify-deploy.js
**Summary**
tests are failing on external contributors, so we need to disable this check for now, until we find a proper solution (using real Netlify instead of my script)
**Result**
log an error on that script for external contributors
> chore(test): close instead of error on external contributors

- README.md
- src/angular/directive.js
- src/autocomplete/typeahead.js
- src/jquery/plugin.js
- src/standalone/index.js
- test/unit/typeahead_spec.js
> feat: add flag for toggling tab autocompletion

- README.md
This should explain how one can use the new `context` parameter to
allow opening results in new tab without sacrificing keyboard
navigation.
> doc(ctrl-click): Add documentation about Ctrl-clicking results

- README.md
**Summary**
The source itself isn't compatible with client v4, since it does some funky things with the user agent that we didn't take the time yet to make compatible, as well as using the callback (not promise) form of .search. In reality those issues aren't that important for users, so I think it makes sense to document the DIY way.
**Result**
An example on how to use client v4 with autocomplete.js
> docs(readme): add compat to v4 in the readme

- karma.conf.js
- package.json
- src/sources/hits.js
- test/playground.html
- test/unit/hits_spec.js
- yarn.lock
**Summary**
This PR adds support for multi-index search to autocomplete.js. With this change only one request is sent instead of multiple ones.
Tests are still missing from this PR but the playground was updated with a new example.
> feat(hits): support multi-index search 

- packages/autocomplete-core/src/completionStateEnhancer.ts
- packages/autocomplete-core/src/createAutocomplete.ts
- packages/autocomplete-core/src/createStore.ts
- packages/autocomplete-core/src/types/store.ts
This extracts the Completion State Enhancer from the store and creates a Store API for State Enhancers.
State Enhancers are hooks to plug to the store to transform the state whenever the state changes.
> refactor(core): extract state enhancers from store

- .circleci/config.yml
- examples/js/package.json
- packages/autocomplete-js/package.json
- packages/autocomplete-plugin-recent-searches/package.json
- ship.config.js
This PR aims at fixing the issues we have building all our packages on CircleCI and publishing them.
I also updated the GitHub settings for this project to require specific tasks to pass before merging.
> chore: update build flow

- packages/autocomplete-core/src/__tests__/getEnvironmentProps.test.ts
Add tests for the `onTouchMove` function returned from `getEnvironmentProps`.
> test(core): add tests for getEnvironmentProps onTouchMove

- bundlesize.config.json
- examples/js/app.tsx
- packages/autocomplete-js/src/__tests__/reverseHighlightHit.test.ts
- packages/autocomplete-js/src/highlight.ts
- packages/autocomplete-plugin-query-suggestions/src/getTemplates.ts
- packages/autocomplete-plugin-recent-searches/src/getTemplates.ts
- packages/autocomplete-preset-algolia/src/highlight/ParseAlgoliaHitParams.ts
- packages/autocomplete-preset-algolia/src/highlight/__tests__/parseAlgoliaHitHighlight.test.ts
- packages/autocomplete-preset-algolia/src/highlight/__tests__/parseAlgoliaHitReverseHighlight.test.ts
- packages/autocomplete-preset-algolia/src/highlight/__tests__/parseAlgoliaHitReverseSnippet.test.ts
- packages/autocomplete-preset-algolia/src/highlight/__tests__/parseAlgoliaHitSnippet.test.ts
- packages/autocomplete-preset-algolia/src/highlight/__tests__/parseAttribute.test.ts
- packages/autocomplete-preset-algolia/src/highlight/parseAlgoliaHitHighlight.ts
- packages/autocomplete-preset-algolia/src/highlight/parseAlgoliaHitSnippet.ts
- packages/autocomplete-preset-algolia/src/highlight/parseAttribute.ts
- packages/website/docs/highlightHit.md
- packages/website/docs/parseAlgoliaHitHighlight.md
- packages/website/docs/parseAlgoliaHitReverseHighlight.md
- packages/website/docs/parseAlgoliaHitReverseSnippet.md
- packages/website/docs/parseAlgoliaHitSnippet.md
- packages/website/docs/reverseHighlightHit.md
- packages/website/docs/reverseSnippetHit.md
- packages/website/docs/snippetHit.md
This is a complete revamp of the highlighting system in both Autocomplete JS and Autocomplete Algolia Preset.
The `highlightHit` function exported from `@algolia/autocomplete-js` does not return a string anymore since we now rely on Virtual DOM and not plain HTML (#381).
(In fact, using an HTML string in a JSX template is known as a security risk because it relies on `dangerouslySetInnerHTML`.)
We now return an array of Virtual Nodes, representing the highlighting structure of the matches.
Usage:
```js
function ProductItem({ hit }: ProductItemProps) {
return (
<div className="aa-ItemContent">
<div className="aa-ItemSourceIcon">
</div>
<div className="aa-ItemTitle">
{highlightHit<ProductHit>({ hit, attribute: 'name' })}
</div>
</div>
);
}
```
Since we don't need to support escaping to …
> feat(highlighting): revamp highlighting system to VDOM

- packages/website/docs/sources.md
- packages/website/docs/templates.md
- packages/website/sidebars.js
This creates a new core concept called "Displaying items with Templates" to further elaborate on the concept.
I've added some comments in the diff for context.
> docs: write "Displaying items with Templates"

- packages/website/docs/sources.md
This fixes a code example using `Array.filter`.
> docs: fix code example

- packages/autocomplete-core/src/__tests__/getEnvironmentProps.test.ts
Add tests for the `onTouchStart` function returned from `getEnvironmentProps`.
> test(core): add tests for getEnvironmentProps onTouchStart

- packages/autocomplete-core/src/__tests__/getInputProps.test.ts
- packages/autocomplete-core/src/__tests__/navigator.test.ts
- test/utils/createNavigator.ts
- test/utils/index.ts
Add tests for `getInputProps` when Ctrl+Enter or Shift+Enter are pressed.
> test(core): add tests for getInputProps when Ctrl+Enter or Shift+Enter are pressed

- packages/autocomplete-core/src/__tests__/getInputProps.test.ts
Add tests for `onFocus`, `onBlur` and `onClick` from `getInputProps`.
> test(core): add tests for onFocus, onBlur and onClick from getInputProps

- packages/website/docs/creating-a-renderer.md
Calling `createAutocomplete` as an initial value of `useRef` would create an unused instance on every rerender.
I hope that's ok 👀
> docs(renderer): replace useRef with useMemo

- packages/website/docs/creating-a-renderer.md
This PR edits the "Creating a Renderer" guide so it is more readable and stylistically in line with the other guides.
> docs: edit "creating a renderer"

- packages/website/docs/debugging.md
This PR edits the Debugging guide.
> docs: edit debugging guide

- packages/website/docs/upgrading.md
This PR makes minimal formatting changes to the upgade. (Overall, looked good already, thanks @francoischalifour !)
> docs: copy-edit upgrade guide

- packages/website/docs/adding-suggested-searches.md
This PR adds a section on how to add categories using the QS plugin.
> docs: add categories to QS guide

- packages/website/docs/createAlgoliaInsightsPlugin.md
This rewrites the `createAlgoliaInsightsPlugin` docs.
> docs(createAlgoliaInsightsPlugin): rewrite docs

- packages/website/docs/createLocalStorageRecentSearchesPlugin.md
This rewrites the `createLocalStorageRecentSearchesPlugin` docs.
> docs(createLocalStorageRecentSearchesPlugin): rewrite docs

- packages/website/docs/autocomplete-js.md
This rewrites the `autocomplete-js` docs.
> docs(autocomplete-js): rewrite docs

- packages/website/docs/reverseHighlightHit.md
This adds a missing comma in a code snippet.
> docs(reverseHighlightHit): add missing comma

- packages/website/docs/plugins.md
This updates the custom plugin example in the docs to reflect the CodeSandbox one.
> docs: update custom plugin example

- examples/github-repositories-custom-plugin/app.tsx
- examples/github-repositories-custom-plugin/createGitHubReposPlugin.tsx
This adapts the GitHub example layout to the latest changes in the classic theme.
> fix(examples): fix GitHub example layout

- packages/autocomplete-core/src/types/AutocompleteOptions.ts
- packages/autocomplete-core/src/types/AutocompletePlugin.ts
- packages/autocomplete-core/src/types/AutocompleteSetters.ts
- packages/autocomplete-core/src/types/AutocompleteSource.ts
- packages/autocomplete-js/src/types/AutocompleteOptions.ts
- packages/autocomplete-js/src/types/AutocompletePlugin.ts
- packages/autocomplete-js/src/types/AutocompleteRenderer.ts
- packages/autocomplete-js/src/types/AutocompleteSource.ts
- packages/autocomplete-js/src/types/AutocompleteState.ts
- packages/autocomplete-js/src/types/HighlightHitParams.ts
- packages/autocomplete-plugin-algolia-insights/src/createAlgoliaInsightsPlugin.ts
- packages/autocomplete-plugin-algolia-insights/src/createSearchInsightsApi.ts
- packages/autocomplete-plugin-query-suggestions/src/createQuerySuggestionsPlugin.ts
- packages/autocomplete-plugin-recent-searches/src/createLocalStorageRecentSearchesPlugin.ts
- packages/autocomplete-plugin-recent-searches/src/createRecentSearchesPlugin.ts
- packages/website/docs/autocomplete-js.md
- packages/website/docs/partials/createAutocomplete-props.md
- packages/website/docs/plugins.md
- packages/website/docs/sources.md
This adds TSDoc for the whole public-facing API to improve DX.
> docs: write TSDoc

- packages/autocomplete-theme-classic/package.json
fixes #586 
see the css example in https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free
> fix(css): mark as side effects
