- README.md
- src/autocomplete/dropdown.js
- src/autocomplete/typeahead.js
- test/unit/dropdown_spec.js
- test/unit/typeahead_spec.js
> Trigger a `autocomplete:empty` when all datasets are empty

- src/autocomplete/dropdown.js
This will make sure that even if there have been no results matching yet
and the minLength has been reached, we correctly display the empty template.
Resolves: #102
> Ensure empty template displays from first keystroke

- src/standalone/index.js
Some jQuery module will register plugins inside Zepto.fn if window.Zepto is present.
So if Zepto was not present before we leaked it in window, now we remove it.
We also set back the previous window.Zepto global if necessary.
Ultimately a better solution would be to be able to not leak Zepto in window by having a good commonJS build of it.
> fix(zepto): do not leak Zepto, restore it if necessary

- README.md
- src/autocomplete/typeahead.js
Hello,
I need an event to be sent when the cursor is removed. Right now, its is not possible to listen to the event 'autocomplete:cursorRemoved' 
Thanks !
> Event sent when cursorRemoved

- src/angular/directive.js
Closes #136
**Summary**
As described in #136 , we're bugging out the behavior of the HTML `autocomplete` attribute.
You can't use `autocomplete="off"` in the current setup, this PR fixes it.
**Result**
Checked in `test/playground_angular.html`.
Attribute mode:
- `autocomplete` =>  our autocomplete triggers
- `autocomplete=""` => our autocomplete triggers
- `autocomplete="off"` => our autocomplete *doesn't* trigger and it correctly prevents the browser from autocompleting
- `data-autocomplete` => our autocomplete triggers
I've also checked that the class mode of the directive still works.
> fix(angular): do not launch the directive if autocomplete has a value

- README.md
- src/angular/directive.js
- src/autocomplete/css.js
- src/autocomplete/dataset.js
- src/autocomplete/dropdown.js
- src/autocomplete/typeahead.js
- src/jquery/plugin.js
- src/standalone/index.js
- test/integration/test.html
- test/integration/test.js
- test/playground.html
- test/playground_angular.html
- test/playground_jquery.html
- test/unit/dropdown_spec.js
- test/unit/typeahead_spec.js
**Summary**
See #135
New parameter: `appendToBody`.
Allows to not wrap the input in `.algolia-autocomplete`.
Automatically repositions itself on resize.
Limitation: requires `hint: false`. Indeed, we're not wrapping the input anymore, so we can't have it behind the input.
**Result**
Without much surprise, it looks the same way:
However, on the playground, it ends up "breaking" the example in `playground.html`.
But this is actually expected based on the bootstrap layout we're using, it's supposed to fail.
```html
<div class="input-group">
<input class="form-control" />
<input class="form-control" />
<span class="input-group-addon">Go</span>
</div>
```
> feat(appendTo): new parameter

- package.json
- src/autocomplete/event_emitter.js
- yarn.lock
Before this commit, we were using setImmediate which was then
polyfilled by webpack in a way that is not efficient
and led to issues like #142 where postMessage was used
no matter what.
Now we use the `immediate` dependency which will first try
to use nextTick, then mutation observers (IE11) then fallback
to postMessage but in a way that should not bug any user
registering for global messages.
fixes #142
> fix(postMessage): avoid using postMessage when feasible

- src/autocomplete/typeahead.js
Zepto's .is only support selectors, not dom nodes: http://zeptojs.com/#is
DOMElement.contains() works on all browsers (IE5).
fixes #144
> fix(zepto): .is() only accepts selectors, reworked code to use pure DOM

- Gruntfile.js
- README.md
- src/autocomplete/dataset.js
- src/autocomplete/dropdown.js
- src/autocomplete/input.js
- src/autocomplete/typeahead.js
- src/standalone/index.js
- test/playground.html
- test/unit/input_spec.js
- test/unit/typeahead_spec.js
- Tested with good results in both NVDA and JAWS.
- VoiceOver has mixed support for these complex controls:
- The normal autocomplete works well,
- The multi sections auto complete won't work (the one in DocSearch)
Demo: http://autocompletejs-a11y.surge.sh/test/playground.html
- Added a temporary fix for #144 (more tests necessary)
- Generated sourcemaps in the standalone build for easier debugging
- Fixed two linting warnings in cc4a403
- Fixed an input ID in the playground (9b3aac9)
- Where should we add tests for the correct behavior/a11y features? Integration tests seem to be the best place but I wasn't sure about it.
- Commit history: let me know if my PR should be broken into multiple ones
> feat(a11y): Add support for screen readers

- README.md
**Summary**
There are no instructions how to install from npm, and as which name it's published
**Result**
added `npm install --save autocomplete.js`
> docs(readme): add npm install instructions

- test/playground.html
When i'm trying to run an interface test i stopped with an exception in console saying that `autocomplete is not defined` so i see that the distribution autocomplete path are wrong.
- Point to correct distribution path.
> Fix playground html dist path

- src/autocomplete/typeahead.js
**Summary**
My case:
And i have a `Show more button`:
The problem:
1º Click in `show more` button
2º More data appended to autocomplete-dataset
3º `_onRedrawn` is called
4º The problem: **var inputRect = `this.$input[0].getBoundingClientRect()`**
As already has a scroll in the page the `bottom` position returned by `inputRect` are much greater than when has no scroll in the page and when are set position of `autocomplete` to `top: 0` and `left: 0` the scroll disappear causing a wrong `top` position:
**What i've done**
Guarantee the autocomplete `top and left` position are reset before calculating the `getBoundingClientRect()`
> Fix redrawn position

- README.md
- src/autocomplete/typeahead.js
- src/standalone/index.js
- test/unit/standalone_spec.js
**Summary**
In my case i need to take the specific `ca-autocomplete` container to verify a custom element and as is possible to have many autocomplete in the same page i don't see other way for get the reference of container through the autocomplete instance. 
**Result**
My playground page:
As you see has more than one autocomplete and the `advanced` has a header template. And in my autocomplete wrapper i made a:
```
this._$autocomplete = this._instance.autocomplete.getWrapper();
``` 
through this new option to get the container and after: 
```
this._$dropdownHeader = this._$autocomplete.querySelector('.autocomplete-dropdown-header');
```
Works perfectly for me.
> getWrapper public method

- src/autocomplete/dataset.js
- test/unit/dataset_spec.js
**Summary**
Currently autocomplete.js triggers the data source function when input is not empty and up/down arrow keys are pressed. A quick demo of the issue can be found at http://jsbin.com/poyofu/edit?html,js,console,output. 
**Result**
Unless the input changes, arrow keys should not trigger redundant requests.
Related to #169
> Prevent source triggering via dropdown update on Up/Down key presses.

- README.md
- src/autocomplete/typeahead.js
- test/unit/typeahead_spec.js
- Retains existing functionality with placeholder/input-id
**Summary**
This change allows more control over the `aria-labelledby` attribute. 
The issue we were running into was specifically related to a State input field. Our placeholder is set to `ST` and the label is `State`. Since the `aria-labelledby` is set to the input id, screen readers would always read `ST` when focusing on the state field. 
**Result**
Review tests for behavior. 
- If `ariaLabelledBy` option set to an id, set `aria-labelledby` to that id
- If `ariaLabelledBy` option set to `false`, do not set `aria-labelledby`
- If no `ariaLabelledBy` option, use id of input field if placeholder is present.  (existing behavior)
> feat(a11y): Add option to control `aria-labelledby` attribute.

- src/autocomplete/dropdown.js
Keeping the selected suggestion in view when using `max-height` and `overflow: scroll` was not working. The css property names being used to calculate the menu height were mistakenly camelCased causing `menuHeight` to be NaN and never triggering the conditional.
> Fixes prop names causing menu height to be NaN

- src/common/utils.js
- test/unit/utils_spec.js
Fixes #243 
I'm getting a JS crash due to an odd useragent from the client. The agent I'm getting is:
```Mozilla/5.0 (iPad; CPU OS 11_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15G77 KurogoVersion/2.7.7 (Kurogo iOS Tablet) KurogoOSVersion/11.4.1 KurogoAppVersion/2.0.1 (com.telerik.TridentUniversity)```
This Kurogo browser is used by universities, and it includes the name of the university in the useragent string. In this case, the university is called Trident. In the `isMsie` code in utils.js, the first line tests for the presence of msie or trident, and the positive side of the unary operator assumes this means it will be checking a standard IE useragent string to get the revision. In my case, that is not the case, so `navigator.userAgent.match(/(msie …
> Handle an odd case with the user agent

- README.md
- examples/basic.html
- src/angular/directive.js
- src/autocomplete/typeahead.js
- src/jquery/plugin.js
- src/standalone/index.js
- test/unit/typeahead_spec.js
In some use-cases, like when you're using autocomplete to make tags on a page, or using the output in any other way than prefilling the query, you don't want the suggested value to show in the input, but would rather like it to be empty.
Before this PR it was basically impossible to have your input not filled, since it came back on blur and a few different places (see `resetInputValue`)
fixes #241 
now there's a new option: 
```js
autocomplete('#input', { clearOnSelected: true }, /* ... */)
```
This makes sure the input clears after selecting, rather dan filling
> feat(clearOnSelected): allow users to clear the input instead of filling

- src/autocomplete/dataset.js
- test/unit/dataset_spec.js
Resolves #131
**Summary**
Throws an error if `suggestions` provided by a dataset are not valid type (`Array`). This helps the developer/user understand why results aren't displayed rather than silently failing.
> Throw err on update if suggestions are invalid type

- README.md
Clarifies API usage via displaying function signatures with named parameters.
Resolves #184
> docs(README): clarify API

- package.json
- yarn.lock
Running `npm run release` with current stack resulted in the following
error for me:
```
/home/tim/.nvm/versions/node/v10.11.0/bin/node[13632]: ../src/node_contextify.cc:628:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
1: 0x8d20d0 node::Abort() [/home/tim/.nvm/versions/node/v10.11.0/bin/node]
2: 0x8d21a5  [/home/tim/.nvm/versions/node/v10.11.0/bin/node]
3: 0x9075f7 node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/home/tim/.nvm/versions/node/v10.11.0/bin/node]
4: 0xb89f5b  [/home/tim/.nvm/versions/node/v10.11.0/bin/node]
5: 0xb8bef2 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) …
```
> fix(release): Update mversion to 1.12

- src/standalone/index.js
**Summary**
Use `aria-label` property from given input element on the new input element.
**Result**
When using standalone version (with places.js for instance) the aria-label on the target input element will be forwarded to the input element created by autocomplete.js.
> fix(standalone): use aria label from input

- src/autocomplete/dataset.js
- test/unit/dataset_spec.js
Fixes: https://github.com/busbud/public-website/issues/8331
**Summary**
It is possible to have Null Pointer Exception, when 'clear' is called immediately after 'destroy' (due to async code somewhere in jquery and user spamming some controls). 
Adding a simple check prevents this error.
Original error:
Some debugging:
**Result**
No more NPE
> Fix NPE when clear is called after destroy

- zepto.js
**Summary**
On some old browsers such as Safari mobile 9, Firefox 52 or Chrome mobile 58, trying to set a read-only property raises an exception `TypeError: setting a property that has only a getter`.
This has been fixed on the Zepto repository, in this [PR](https://github.com/madrobby/zepto/pull/1218). But since no release has been done, it's not available via Semver.
This PR applies the above patch to the versioned Zepto file.
> Catch exceptions while assigning event.timeStamp

- src/common/parseAlgoliaClientVersion.js
- test/unit/parseAlgoliaClientVersion_spec.js
This fixes #301 by supporting user agents for `algoliasearch` >= 3.33.0.
> fix(algolia): parse user agents with new search clients

- README.md
**Summary**
The README currently says that "The autocomplete.js library must be included after […] Zepto […]".
So I thought I had to load `Zepto` first, and then `autocomplete.js`.
But it looks like `Zepto` is [already embedded into `dist/autocomplete.js`](https://github.com/algolia/autocomplete.js/blob/master/dist/autocomplete.js#L169).
I checked it works when I load `autocomplete.js` without loading `Zepto` before.
**Result**
Updated doc.
> Installation doc fix for standalone version

- examples/js/app.js
- packages/autocomplete-core/src/getDefaultProps.ts
- packages/autocomplete-core/src/stateReducer.ts
- packages/autocomplete-core/src/types/api.ts
- packages/website/docs/partials/createAutocomplete-props.md
This adds a debug mode to Autocomplete Core (and therefore Autocomplete JavaScript) so that it's easier to inspect the dropdown which doesn't close when the blur event occurs.
This is a feature that was implemented in Autocomplete v0 and that several developers requested in this version as well.
> feat(core): introduce debug mode

- bundlesize.config.json
- examples/js/app.js
- examples/js/autocomplete.css
- examples/js/style.css
- packages/autocomplete-js/src/autocomplete.ts
- packages/autocomplete-js/src/debounce.ts
- packages/website/docs/autocomplete-js.md
This introduces a new API for Autocomplete JavaScript called `dropdownPlacement`.
I went for the terminology "placement" because [Popper.js](https://popper.js.org/docs/v2/constructors/#placement) uses this term, and `"start" | "end"` like [`align-content`](https://css-tricks.com/almanac/properties/a/align-content/) from the Flexible Box Layout module.
Fall back to `"full-width"` on mobile.
- Open the PR sandbox
- Uncomment the `dropdownPlacement` of `autocomplete`
> feat(js): introduce `dropdownPlacement` API

- examples/js/autocomplete.css
- packages/autocomplete-js/src/autocomplete.ts
- packages/autocomplete-js/src/concatClassNames.ts
- packages/autocomplete-js/src/types/index.ts
- packages/website/docs/autocomplete-js.md
This introduces the `classNames` API to `autocomplete-js` to append class names to each DOM element that Autocomplete creates. The name `classNames` was used to align with the [`className`](https://developer.mozilla.org/en-US/docs/Web/API/Element/className) Web API.
This API is useful to map classnames from your website or CSS integration (e.g., Tailwind) to Autocomplete directly.
> feat(js): introduce `classNames` API

- packages/autocomplete-core/src/createAutocomplete.ts
For now, `autocompleteInstance.refresh()` always open the dropdown no matter if it was already closed or not.
This PR fixes the bug so that it can remain closed if it was.
> fix(refresh): remain current value of isOpen

- packages/autocomplete-core/src/types/api.ts
We assign [default values](https://github.com/algolia/autocomplete.js/blob/637d23ecb82f88b6de686b76657fe53a8acf119d/packages/autocomplete-core/src/getDefaultProps.ts#L85-L104) for each navigator property so we expect `Partial<Navigator>`, not `Navigator` from users.
> fix(core): turn public `navigator` type to partial

- packages/autocomplete-preset-algolia/src/search/getAlgoliaHits.ts
- packages/autocomplete-preset-algolia/src/search/getAlgoliaResults.ts
- packages/autocomplete-preset-algolia/src/search/search.ts
This fixes some wrong types in the `getAlgoliaResults` function. We now make sure to receive records as inputs and to return hits (being their returned value with highlighting and snippetting).
> fix(algolia): fix `getAlgoliaResults` typings

- packages/autocomplete-preset-algolia/src/search/__tests__/search.test.ts
**Summary**
I think I needed this before lerna ran, but in either case, I think it makes more sense to assert the lcoal version is used than the one from @algolia/autocomplete-core
**Result**
no dependencies are used within the test of autocomplete.js
> test(js): use local version in assertion

- packages/autocomplete-core/src/types/api.ts
- packages/autocomplete-core/src/types/wrappers.ts
- packages/autocomplete-js/src/types/index.ts
**Summary**
it's complex to type when an item is either a promise or not (and after #331 maybe arrays or not) from the typings, so refactoring this into a shared type makes sense
**Result**
add the complexity for types which are allowed to be promises or not into a single helper object
> chore(ts): add MaybePromise wrapper to make APIs shorter to read

- packages/autocomplete-core/src/createStore.ts
- packages/autocomplete-core/src/onKeyDown.ts
- packages/autocomplete-core/src/stateReducer.ts
- packages/autocomplete-core/src/types/store.ts
This simplifies the signature of the store and the reducer, to be more conformed to the state reducer pattern (see React's [`useReducer`](https://reactjs.org/docs/hooks-reference.html#usereducer) as example):
- **Store**
- Remove `this.state` and relies on scoped `state` variable, non-accessible from the outside
- **Reducer**
- Only accept `(state, action) => state`
- An action is now defined as `{ type, payload, props }` where props are the options passed to Autocomplete
This standardizes the state reducer signature if we were to make this a public API later.
>  refactor(core): update state reducer signature

- packages/autocomplete-core/src/createStore.ts
- packages/autocomplete-core/src/types/api.ts
This PR adds a new prop `prevState` to `onStateChange`.
With this addition, users don't have to keep track of the previous state for comparison.
For example,
```js
onStateChange({ state }) {
if (state.query !== queryRef.current) {
queryRef.current = state.query;
props.refine(state.query);
}
},
```
becomes
```js
onStateChange({ state, prevState }) {
if (state.query !== prevState.query) {
props.refine(state.query);
}
},
```
> feat(core): provide previous state to `onStateChange`

- packages/autocomplete-core/src/onInput.ts
When the query is `abcdef`, and move the cursor in the middle of `input` element and type `Z`, then it will become `abcZdef`. Here the cursor is supposed to be right after `Z`, but it was wrongly moved to the end of the query.
The problem comes from the order of 
```
setHighlightedIndex(props.defaultHighlightedIndex);
setQuery(query);
```
When `setHighlightedIndex()` is called, the `input.value` is already `abcZdef`, but `store.getState().query` is still `abcdef` because the query hasn't been updated to the store yet.
So `input.value` becomes `abcdef`. Shortly after because of `setQuery`, `input.value` becomes `abcZdef` again.
In this PR, the order is been reversed, which now correctly sets the query first, and then proceed with the rest. It doesn't move cursor anymore.
> fix: cursor stays where it's supposed to be

- ship.config.js
This PR includes `@algolia/autocomplete-plugin-recent-searches` in the shipjs config.
> chore: include recent searches plugin in the next release

- packages/website/docs/autocomplete-js.md
- packages/website/docs/sources.md
This PR fixes `autocomplete = autocomplete(` error.
> docs: rename the assigned variable

- packages/autocomplete-core/src/__tests__/getAutocompleteSetters.test.ts
- packages/autocomplete-core/src/__tests__/utils.test.ts
- packages/autocomplete-core/src/getAutocompleteSetters.ts
- packages/autocomplete-core/src/getDefaultProps.ts
- packages/autocomplete-core/src/types/api.ts
- packages/autocomplete-core/src/utils.ts
**Summary**
It flattens the result of getSuggestions. this is useful, since it allows getAlgoliaHits to be used top-level, but also within a single source, without having to take the first element of the array manually
**Result**
you can use getAlgoliaHits top-level in getSources, but also in getSuggestions (like in the docs: https://algolia-autocomplete.netlify.app/docs/autocomplete-js)
> fix(getSuggestions): allow nested arrays to be returned

- packages/autocomplete-core/src/getDefaultProps.ts
- packages/autocomplete-core/src/stateReducer.ts
- packages/autocomplete-core/src/types/state.ts
This removes the undocumented `statusContext` API.
This state property was originally added to my POC to track which error happened last in the lifecycle. Since we don't leverage this for now, let's remove it. If users express the need for such a feature, we can add the feature back.
> feat(core): remove `statusContext` API

- .codesandbox/ci.json
This will use the playground from the local code rather than from the next branch in our PRs.
> chore(ci): use branch sandbox on deployments

- examples/js/index.html
- examples/js/index.ts
Parcel picks the `source` field of the monorepo packages and thus doesn't apply the Babel config to replace our `__DEV__` global expression. We therefore need to manually override it in the example app.
See https://twitter.com/devongovett/status/1134231234605830144
> docs(example): provide `__DEV__` replacement

- bundlesize.config.json
- packages/autocomplete-plugin-recent-searches/src/createLocalStorageRecentSearchesPlugin.ts
- packages/autocomplete-plugin-recent-searches/src/createStore.ts
- packages/autocomplete-plugin-recent-searches/src/getTemplates.ts
- packages/autocomplete-plugin-recent-searches/src/types/Highlighted.ts
- packages/autocomplete-plugin-recent-searches/src/types/RecentSearchesHit.ts
- packages/autocomplete-plugin-recent-searches/src/types/index.ts
- packages/autocomplete-plugin-recent-searches/src/usecases/localStorage/search.ts
This adds support for search highlighting in the Recent Searches.
> feat(recent-searches): add search highlighting

- .eslintrc.js
- packages/autocomplete-js/src/autocomplete.ts
This batches state changes to limit DOM mutations.
Every time we call a setter in `autocomplete-core` (e.g., in `onInput` with `setSelectedItemId`, `setQuery`, `setCollection`, etc.), the core `onStateChange` function is called. We don't need to be notified of all these state changes to render.
As an example:
- without debouncing: "iphone case" query → 85 renders
- with debouncing: "iphone case" query → 12 renders
> feat(js): batch DOM updates

- packages/autocomplete-core/src/getPropGetters.ts
- packages/autocomplete-core/src/types/getters.ts
- packages/autocomplete-js/src/autocomplete.ts
- packages/website/docs/creating-a-renderer.md
- packages/website/docs/prop-getters.md
This renames the `getEnvironmentProps` param from `searchBoxElement` to `formElement`, which fits better the other namings (e.g., `getFormProps`).
BREAKING CHANGE.
> feat(core): rename `searchBoxElement` to `formElement`

- .eslintrc.js
- babel.config.js
- examples/js/env.ts
- jest.config.js
- packages/autocomplete-js/global.d.ts
- packages/autocomplete-js/src/__tests__/fixtures/query-suggestions.json
- packages/autocomplete-js/src/__tests__/positioning.test.ts
- packages/autocomplete-js/src/autocomplete.ts
- packages/autocomplete-js/src/components/Panel.ts
- packages/autocomplete-js/src/getPanelPositionStyle.ts
This PR makes sure that the panel position always remains below the root element, even after a UI change.
We used to calculate the position of the panel only when the library was instantiated. We now recalculate its position when it needs to be opened.
> fix(js): calculate panel position before opening

- packages/website/docs/creating-a-renderer.md
Line 102 - removed the block wrapper to fix an "Unexpected block statement surrounding arrow body; move the returned value immediately after the `=>`" error.
Line 102 - removed reference to index to fix the "'index' is already declared in the upper scope" and "'index' is defined but never used" errors.
> feat(js): ESLint error fixes

- packages/autocomplete-plugin-recent-searches/src/usecases/localStorage/search.ts
**Summary**
The previous RegEx was not escaping parentheses or question marks in recent searches.
**Actual behavior**
- Parentheses: Throw an error when a parenthesis is typed `invalid regex`
- Question marks: Duplicates the question mark when it's typed (e.g. with query `Amazon?` result is `Amazon??`)
and then throwing error while trying to replace the `item.query
> fix(recent-searches): escape highlighted query regex

- packages/website/docs/keyboard-navigation.md
This PR rewrites the **Integrating keyboard navigation** guide.
It adds an introduction, and clarifies the concept.
I've tried to clarify what is meant by keyboard _navigation_ in this context (the navigation to a URL via the keyboard), as users may think this page is about keyboard accessibility (which Autocomplete provides by default).
I've also tried to explain why you would need to implement the API, and when to leave the default implementation alone.
> docs: rewrite "Integrating keyboard navigation"

- packages/website/docs/context.md
This PR rewrites the **Accessing data with Context** core concept.
It adds an introduction, and clarifies the concept.
I've added a **Reference** section to document the shape of both `context` and `setContext`. I've described the expanded types and dropped generics so it's still useful for users looking for parameter shape or return types (while `StateUpdater<TState>` would force them to look it up in the code, or for us to document it). Let me know if you'd like to go with a different approach.
Regarding `setContext`, we should document where it's provided (which functions expose it) so users know where they can leverage it. Could you list them all @francoischalifour?
I'd also like to show a simple example of using it in a plugin (just to illustrate the last point). It doesn't have to …
> docs: rewrite "Accessing data with Context"

- packages/website/docs/state.md
This PR rewrites the **Controlling behavior with State** core concept.
It adds an introduction, and clarifies the concept.
@francoischalifour I wrote a practical example for using getters, as the link to the CodeSandbox in the Google Doc didn't show any (maybe it was the wrong link?). Let me know if you had something different in mind.
> docs: rewrote "Controlling behavior with State"

- packages/website/docs/sources.md
This rewrites and clarifies "Populating autocomplete with Sources", and add missing parts.
I have some uncertainties regarding some parts of the docs, which I detailed directly in the diff.
> docs: rewrite "Populating autocomplete with Sources"

- packages/website/docs/context.md
- packages/website/docs/keyboard-navigation.md
- packages/website/docs/state.md
This switches references to `autocomplete-core` with `autocomplete-js` in the core concepts.
> docs: switch core usage with autocomplete-js

- packages/autocomplete-core/src/__tests__/getSources.test.ts
Add tests for `default source implementation` and `concat getSources from plugins`.
_I'm not sure if this is the expected the behavior, any tips appreciated!_
> test(core): add tests for `default source implementation` and `concat getSources from plugins`

- packages/autocomplete-js/src/utils/mergeClassNames.ts
**Summary**
When `onResize` effect was triggered, classes were merged even if they had the same name.
This should fix this issue
> fix(mergeClassNames): prevent classes with the same name being merged

- packages/website/docs/help.md
This PR writes the last introduction page, "Help and discussion".
I was wondering if we should also link the [Discord](https://discord.gg/tXdr5mP). 
I think it's a good idea if it's actively monitored. My only fear would be that it could get **too** busy, but I guess we can cross that bridge if/when we get to it. 😅
> docs: write "help and discussion" page

- packages/autocomplete-js/src/__tests__/autocomplete.test.ts
- packages/autocomplete-js/src/autocomplete.ts
**Summary**
When `openOnFocus` is `false`, the `empty` source template or `renderEmpty` was still rendered.
> fix(js): ignore empty template with no query and `openOnFocus`

- bundlesize.config.json
- packages/autocomplete-js/src/highlight.ts
- packages/autocomplete-preset-algolia/src/highlight/ParseAlgoliaHitParams.ts
- packages/autocomplete-preset-algolia/src/highlight/__tests__/parseAlgoliaHitHighlight.test.ts
- packages/autocomplete-preset-algolia/src/highlight/__tests__/parseAlgoliaHitReverseHighlight.test.ts
- packages/autocomplete-preset-algolia/src/highlight/__tests__/parseAlgoliaHitReverseSnippet.test.ts
- packages/autocomplete-preset-algolia/src/highlight/__tests__/parseAlgoliaHitSnippet.test.ts
- packages/autocomplete-preset-algolia/src/highlight/getAttributeValueByPath.ts
- packages/autocomplete-preset-algolia/src/highlight/parseAlgoliaHitHighlight.ts
- packages/autocomplete-preset-algolia/src/highlight/parseAlgoliaHitSnippet.ts
- packages/website/docs/highlightHit.md
- packages/website/docs/parseAlgoliaHitHighlight.md
- packages/website/docs/parseAlgoliaHitReverseHighlight.md
- packages/website/docs/parseAlgoliaHitReverseSnippet.md
- packages/website/docs/parseAlgoliaHitSnippet.md
**Summary**
Allow `attribute` key to receive a `string[]` containing the path of the highlighted element in the hit.
**TypeScript**
I couldn't find a good way to implement deep object pathing, so it's not typed for now. It also looks like that a `PathOf` type is 
still discussed.
> feat(highlighting): support array syntax for nested attributes

- .eslintrc.js
Add the ESLint [`curly`](https://eslint.org/docs/rules/curly) rule. No changes are necessary for the codebase since it was already following this convention.
> chore(lint): add curly rule

- .stylelintrc.json
- bundlesize.config.json
- examples/js/app.tsx
- examples/js/darkMode.ts
- examples/js/index.html
- examples/js/package.json
- examples/js/shortcutsPlugin.tsx
- examples/js/style.css
- examples/react-renderer/src/App.css
- examples/react-renderer/src/App.tsx
- examples/react-renderer/src/Autocomplete.tsx
- examples/react-renderer/src/index.css
- examples/react-renderer/tsconfig.json
- package.json
- packages/autocomplete-js/src/types/AutocompletePlugin.ts
- packages/autocomplete-js/src/types/index.ts
- packages/autocomplete-plugin-query-suggestions/src/getTemplates.ts
- packages/autocomplete-plugin-recent-searches/src/getTemplates.ts
- packages/autocomplete-theme-classic/src/theme.scss
- yarn.lock
Bring an easy to customize theme taking advantage of css variables.
SCSS is written to be easily readable and customizable by using indentation. Output CSS needs some work to reduce the unnecessary levels of specificity. (@root ??)
> Theme Classic SCSS

- packages/autocomplete-core/src/__tests__/completion.test.ts
- packages/autocomplete-core/src/__tests__/createAutocomplete.test.ts
- packages/autocomplete-core/src/__tests__/debug.test.ts
- packages/autocomplete-core/src/__tests__/defaultSelectedItemId.test.ts
- packages/autocomplete-core/src/__tests__/getEnvironmentProps.test.ts
- packages/autocomplete-core/src/__tests__/getFormProps.test.ts
- packages/autocomplete-core/src/__tests__/getInputProps.test.ts
- packages/autocomplete-core/src/__tests__/getPanelProps.test.ts
- packages/autocomplete-core/src/__tests__/getSources.test.ts
- packages/autocomplete-core/src/__tests__/initialState.test.ts
- packages/autocomplete-core/src/__tests__/onStateChange.test.ts
- packages/autocomplete-core/src/__tests__/openOnFocus.test.ts
- packages/autocomplete-core/src/__tests__/refresh.test.ts
- packages/autocomplete-core/src/__tests__/setCollections.test.ts
- packages/autocomplete-core/src/__tests__/stallThreshold.test.ts
- packages/autocomplete-core/src/createAutocomplete.ts
- packages/autocomplete-core/src/createStore.ts
- packages/autocomplete-core/src/types/AutocompleteOptions.ts
- packages/autocomplete-core/src/types/AutocompletePlugin.ts
- packages/autocomplete-js/src/types/AutocompleteOptions.ts
This forwards the setters and the `refresh` APIs to all the lifecycle hooks, including `onStateChange` and the plugin's `subscribe` function.
It allows for a more powerful plugins integration, required for Autocomplete Tags for example.
```tsx
function createTagPlugin<TItem extends {}>({
getTagLabel,
onTag,
}: CreateTagPluginProps<TItem>): AutocompletePlugin<TItem> {
const tags = [];
return {
subscribe({ onSelect, refresh, setQuery }) {
onSelect((params) => {
tags.push(getTagLabel(params));
setQuery("");
refresh();
onTag(params);
});
},
onStateChange({ refresh }) {
render(
<ul className="aa-InputTagList">
{tags.map((tag, index) => (
<li key={index} className="aa-InputTagItem">
<AutocompleteTag
label={tag}
onRemove={() => {
tags.splice(tags.indexOf(tag), 1);
refresh();
}}
/>
</li>
))} …
```
> feat(core): pass scoped API to lifecycle hooks

- examples/js/app.tsx
- examples/js/shortcutsPlugin.tsx
- packages/autocomplete-core/src/__tests__/concurrency.test.ts
- packages/autocomplete-core/src/__tests__/getInputProps.test.ts
- packages/autocomplete-core/src/__tests__/getSources.test.ts
- packages/autocomplete-core/src/__tests__/stallThreshold.test.ts
- packages/autocomplete-core/src/types/AutocompleteSource.ts
- packages/autocomplete-core/src/utils/__tests__/getNormalizedSources.test.ts
- packages/autocomplete-core/src/utils/getNormalizedSources.ts
- packages/autocomplete-js/src/__tests__/autocomplete.test.ts
- packages/autocomplete-js/src/__tests__/positioning.test.ts
- packages/autocomplete-js/src/render.tsx
- packages/autocomplete-js/src/types/AutocompleteSource.ts
- packages/autocomplete-plugin-query-suggestions/src/createQuerySuggestionsPlugin.ts
- packages/autocomplete-plugin-recent-searches/src/createLocalStorageRecentSearchesPlugin.ts
- packages/autocomplete-plugin-recent-searches/src/createRecentSearchesPlugin.ts
- packages/website/docs/autocomplete-js.md
- packages/website/docs/createAutocomplete.md
- packages/website/docs/creating-a-renderer.md
- packages/website/docs/keyboard-navigation.md
- packages/website/docs/sources.md
- test/utils/createSource.ts
**Summary**
- Add a required `sourceId` option to `AutocompleteSource` interface in `core`
- Provide `data-autocomplete-source-id` based on `sourceId` on source DOM container (section)
- Update `getSources` related tests
- Update docs
> feat(sourceId): Add `sourceId` to provide `data-autocomplete-source-id` on `section` source container

- packages/website/docs/sources.md
- packages/website/docs/using-dynamic-sources-based-on-query.md
- packages/website/sidebars.js
- packages/website/src/components/AutocompleteProduct.tsx
- packages/website/src/components/AutocompleteStaticItem.tsx
This PR extracts a section from the sources Core Concept and creates a guide from it.
The reason to put it in its own guide is to emphasize this as a UX recommendation. Future iterations of this guide docs could add:
- using Favorite Searches
- using Context
> docs: add dynamic sources guide

- examples/js/app.tsx
- packages/autocomplete-plugin-query-suggestions/src/getTemplates.tsx
- packages/autocomplete-plugin-recent-searches/src/getTemplates.tsx
- packages/autocomplete-theme-classic/src/theme.scss
This adds a container that wraps the item action button. It enables designs with multiple actions.
Using a dummy additional icon for Query Suggestions:
> feat(js): wrap item action buttons in container

- packages/autocomplete-core/src/__tests__/getInputProps.test.ts
- packages/autocomplete-core/src/onInput.ts
- packages/autocomplete-core/src/types/AutocompleteOptions.ts
- packages/website/docs/partials/createAutocomplete-props.md
The `onInput` user param was originally introduced to enable controlled mode, but we've managed to create all the search experiences we wanted without this option. We can therefore remove it before public release.
> feat(core): remove `onInput` option

- packages/website/docs/using-react.md
- packages/website/docs/using-vue.md
- packages/website/sidebars.js
This PR creates guides on using the Autocomplete library in a Vue and React application.
(It was originally going to add just the Vue guide, hence the name.)
> docs: add "Using Autocomplete with Vue/React" guides

- packages/website/docs/getting-started.md
- packages/website/src/components/ProductItem.tsx
This PR updates the getting started guide so:
- It includes information on the classic theme package
- It creates and showcases an e-commerce rather than documentation example
- It provides more explicit suggestions for "going further"
Once this is merged into `next`, the [guides PR](https://github.com/algolia/autocomplete.js/pull/430/files) should make sure to use updated links for the guides in "going further".
> docs: update Getting Started guide

- examples/js/app.tsx
- packages/autocomplete-js/src/__tests__/autocomplete.test.ts
- packages/autocomplete-js/src/__tests__/renderEmpty.test.ts
- packages/autocomplete-js/src/__tests__/renderNoResults.test.ts
- packages/autocomplete-js/src/autocomplete.ts
- packages/autocomplete-js/src/getDefaultOptions.ts
- packages/autocomplete-js/src/render.tsx
- packages/autocomplete-js/src/types/AutocompleteClassNames.ts
- packages/autocomplete-js/src/types/AutocompleteOptions.ts
- packages/autocomplete-js/src/types/AutocompleteSource.ts
- packages/autocomplete-theme-classic/src/theme.scss
- packages/website/docs/autocomplete-js.md
- packages/website/docs/autocomplete-theme-classic.md
- packages/website/docs/plugins.md
- packages/website/docs/templates.md
- packages/website/docs/upgrading.md
The name `empty` was rather confusing and `noResults` reflects better when this template is displayed.
This renames all params that contain `empty` to `noResults`:
- `templates.empty` → `templates.noResults`
- `renderEmpty` → `renderNoResults`
- `.aa-SourceEmpty` → `.aa-SourceNoResults`
> feat(js): rename `empty` to `noResults`

- packages/website/docs/creating-multi-source-autocompletes.md
- packages/website/src/components/AutocompleteExample.tsx
This updates the Multiple Result Types guide with a better example component design and documents how to add `header` templates to QS and RS plugins.
> docs(guides): update Multiple Result Types guide

- packages/website/docs/adding-recent-searches.md
- packages/website/docs/adding-suggested-searches.md
This adds a section in both the Query Suggestions and the Recent Searches guide to explain how to turn items into links. This is a common use case when using Autocomplete as an entry point to your search page.
> docs(guides): add section to use QS and RS as links

- bundlesize.config.json
- examples/js/app.tsx
- examples/js/categoriesPlugin.tsx
- packages/autocomplete-js/src/__tests__/getAlgoliaFacetHits.test.ts
- packages/autocomplete-js/src/getAlgoliaFacetHits.ts
- packages/autocomplete-js/src/index.ts
- packages/autocomplete-preset-algolia/src/index.ts
- packages/autocomplete-preset-algolia/src/search/UserAgent.ts
- packages/autocomplete-preset-algolia/src/search/__tests__/search.test.ts
- packages/autocomplete-preset-algolia/src/search/getAlgoliaFacetHits.ts
- packages/autocomplete-preset-algolia/src/search/searchForFacetValues.ts
- packages/website/docs/getAlgoliaFacetHits-js.md
- packages/website/docs/getAlgoliaFacetHits.md
- packages/website/docs/getAlgoliaHits-js.md
- packages/website/docs/getAlgoliaResults-js.md
- packages/website/docs/getAlgoliaResults.md
- packages/website/sidebars.js
The `getAlgoliaFacetHits` function is an additional search util to our `@algolia/autocomplete-preset-algolia` package.
We now have:
- `getAlgoliaHits`
- `getAlgoliaResults`
- `getAlgoliaFacetHits`
This function is useful to search for facets in the Autocomplete panel. Later, it will be useful when using Autocomplete Tags to refine the query to a category as a first step of the flow.
The `getAlgoliaFacetHits` function returns a similar format to React InstantSearch's facet hits from `connectRefinementList`. This allows to use highlighting utils (e.g., `highlightHit`) with facet hits.
```json
[
{
"count": 507,
"label": "Mobile phones",
"_highlightResult": {
"label": {
"value": "Mobile <em>phone</em>s"
}
}
},
{
"count": 63,
"label": "Phone cases",
"_highlightResult": {
"label": {
"value": …
```
> feat(algolia): add `getAlgoliaFacetHits` preset

- packages/autocomplete-core/src/__tests__/debug.test.ts
- packages/autocomplete-core/src/__tests__/getEnvironmentProps.test.ts
- packages/autocomplete-core/src/__tests__/getFormProps.test.ts
- packages/autocomplete-core/src/__tests__/getInputProps.test.ts
- packages/autocomplete-core/src/__tests__/openOnFocus.test.ts
- packages/autocomplete-core/src/stateReducer.ts
This improves the experience when using `openOnFocus` on slow networks. The panel only opens when `shouldPanelOpen` returns `true`.
The default implementation for `shouldPanelOpen` is to return `true` when there are some items. As a result, the panel won't open on focus as long as there's no results. This means that the panel won't open with empty content.
> fix(core): compute open state on focus with `shouldPanelOpen`

- packages/autocomplete-js/src/autocomplete.ts
- packages/autocomplete-js/src/render.tsx
- packages/autocomplete-theme-classic/src/theme.scss
- packages/website/docs/autocomplete-theme-classic.md
This scrolls to the top of the panel when the query changes (i.e., when new results come in) so that users don't have to.
We introduce a new CSS utility class in the theme called `.aa-Panel--Scrollable` which hints Autocomplete that this is the container responsible for displaying the list of items.
By default, this CSS class is attached to `.aa-PanelLayout`, but when we introduce the Preview Panel plugin, it will be attached to the left child of `.aa-PanelLayout`.
Whenever the query changes, we scroll to the top of this scrollable container.
> feat(js): scroll to top when query changes

- packages/autocomplete-js/src/__tests__/api.test.ts
- packages/autocomplete-js/src/__tests__/classNames.test.ts
- packages/autocomplete-js/src/__tests__/panelContainer.test.ts
- packages/autocomplete-js/src/__tests__/panelPlacement.test.ts
Add multiple tests for:
* autocomplete API:
* `setActiveItemId`
* `setQuery`
* `setCollections`
* `setIsOpen`
* `setStatus`
* `setContext`
* `update`
* `destroy`
* `classnames` option
* `panelContainer` option
* `panelPlacement` option
> test(js): add tests for API and options

- packages/website/docs/creating-a-renderer.md
Some people get confused why this guide seem complex compared to using Preact. It's because it's relying on `autocomplete-core` to create your own Autocomplete Renderer, which you shouldn't need if you haven't hit limitations with Autocomplete JS.
> docs(renderer): add usage warning

- packages/website/docs/autocomplete-theme-classic.md
- packages/website/docs/getting-started.mdx
- packages/website/docs/partials/install-classic-theme.md
This rewrites the Classic theme docs.
It also moves the installation part into a partial so we can reuse it across the docs.
> docs(autocomplete-theme-classic): rewrite docs

- packages/website/docs/createAutocomplete.md
- packages/website/docs/partials/createAutocomplete-props.md
- packages/website/sidebars.js
This rewrites the `createAutocomplete` docs.
I've moved it after `autocomplete-js` because users who browse the docs fast may click on the first item and move forward with it without paying much attention. This further ensures they don't start using `autocomplete-core` with no good reason.
> docs(createAutocomplete): rewrite docs

- packages/website/docs/partials/preset-algolia/note.md
This adds a common note for all functions under `autocomplete-preset-algolia`.
> docs(autocomplete-preset-algolia): add common note

- packages/website/docs/api.md
This removes the unused `Draft` import.
> docs(api): remove draft import

- examples/query-suggestions-with-rich-hits/app.tsx
This is a proposal to improve the "Query Suggestions with Rich Hits" example (#486).
Some styles were inlined because they will be covered from the Classic Theme soon.
> doc(sandbox): patch Query Suggestions with Rich Hits

- packages/website/docs/getAlgoliaFacetHits-js.md
- packages/website/docs/getAlgoliaFacetHits.md
- packages/website/docs/partials/preset-algolia/getAlgoliaFacetHits/intro.md
- packages/website/docs/partials/preset-algolia/note.md
This rewrites the `getAlgoliaFacetHits` docs for both `autocomplete-preset-algolia` and `algolia-js`.
> docs(getAlgoliaFacetHits): rewrite guides

- packages/website/docs/createQuerySuggestionsPlugin.md
This rewrites the `createQuerySuggestionsPlugin` docs.
> docs(createQuerySuggestionsPlugin): rewrite docs

- packages/website/docs/highlightHit.md
- packages/website/docs/parseAlgoliaHitHighlight.md
- packages/website/docs/partials/preset-algolia/note.md
This rewrites the `parseAlgoliaHitHighlight` docs for `autocomplete-preset-algolia` and `highlightHit` for `algolia-js`.
> docs(parseAlgoliaHitHighlight): rewrite guides

- packages/website/docs/createRecentSearchesPlugin.md
- packages/website/sidebars.js
This rewrites the `createRecentSearchesPlugin` docs.
I've added inline comments on some changes for easier reviewing.
> docs(createRecentSearchesPlugin): rewrite docs

- packages/website/docusaurus.config.js
This PR removes the "API" link from the top nav, per user feedback.
> docs: remove API from top nav

- packages/website/docs/getAlgoliaResults-js.md
- packages/website/docs/getAlgoliaResults.md
- packages/website/docs/partials/preset-algolia/getAlgoliaResults/intro.md
- packages/website/docs/partials/preset-algolia/note.md
This rewrites the `getAlgoliaResults` docs for both `autocomplete-preset-algolia` and `algolia-js`.
> docs(getAlgoliaResults): rewrite guides

- packages/website/docs/parseAlgoliaHitReverseHighlight.md
- packages/website/docs/partials/preset-algolia/note.md
- packages/website/docs/reverseHighlightHit.md
This rewrites the `parseAlgoliaHitReverseHighlight` docs for `autocomplete-preset-algolia` and `reverseHighlightHit` for `algolia-js`.
> docs(parseAlgoliaHitReverseHighlight): rewrite guides

- examples/query-suggestions-with-inline-categories/app.tsx
- packages/autocomplete-plugin-query-suggestions/src/createQuerySuggestionsPlugin.ts
- packages/website/docs/adding-suggested-searches.mdx
- packages/website/docs/createQuerySuggestionsPlugin.md
- packages/website/docs/introduction.mdx
This renames the Query Suggestions plugin option `categoriesLimit` to `itemsWithCategories`.
(The previous options were also inverted in the QS plugin, so this rename fixes it.)
- https://github.com/algolia/autocomplete/pull/468#discussion_r584529644
> fix(qs): rename `categoriesLimit` to `itemsWithCategories`

- packages/autocomplete-js/src/__tests__/autocomplete.test.ts
- packages/autocomplete-js/src/render.tsx
- packages/autocomplete-js/src/types/AutocompleteRender.ts
This adds an API to easily retrieve generated UI elements to manipulate the panel UI.
Finding the right source to render in the panel was cumbersome, and sometimes created friction to generate advanced conditional layouts.
We use the `sourceId` (which is required) as the key to the `elements` record:
```ts
const querySuggestionsPlugin = elements.querySuggestionsPlugin; // or
const querySuggestionsPlugin = elements['querySuggestionsPlugin']; // or
const { querySuggestionsPlugin } = elements;
```
This makes flows easier to render because with flows, some key values can be `undefined` (because `getSources` doesn't return them). In JSX, rendering `undefined` renders nothing, which is convenient.
```ts
import { render } from 'preact';
autocomplete({
// ...
plugins: [recentSearchesPlugin, …
```
> feat(js): pass `elements` record to `render`

- packages/website/docs/parseAlgoliaHitSnippet.md
- packages/website/docs/partials/preset-algolia/note.md
- packages/website/docs/snippetHit.md
This rewrites the `parseAlgoliaHitSnippet` docs for `autocomplete-preset-algolia` and `snippetHit` for `algolia-js`.
> docs(parseAlgoliaHitSnippet): rewrite guides

- packages/website/docs/highlightHit.md
- packages/website/docs/parseAlgoliaHitHighlight.md
- packages/website/docs/parseAlgoliaHitReverseHighlight.md
- packages/website/docs/parseAlgoliaHitReverseSnippet.md
- packages/website/docs/parseAlgoliaHitSnippet.md
- packages/website/docs/reverseSnippetHit.md
- packages/website/docs/snippetHit.md
This unifies the examples across all Algolia preset helpers.
> docs(autocomplete-preset-algolia): unify examples

- packages/autocomplete-js/src/autocomplete.ts
- packages/autocomplete-js/src/getPanelPlacementStyle.ts
This removes all `window` references in Autocomplete JS to support SSR.
> fix(js): remove `window` references

- packages/website/docs/autocomplete-js.md
In #490 we introduced the `elements` API to easily pick which source to display in the panel based on its `sourceId`. This adds documentation for it.
> docs(js): add doc for `elements` API

- examples/recently-viewed-items/recentlyViewedItemsPlugin.tsx
- packages/autocomplete-plugin-query-suggestions/src/createQuerySuggestionsPlugin.ts
- packages/autocomplete-plugin-recent-searches/src/createRecentSearchesPlugin.ts
- packages/website/docs/createLocalStorageRecentSearchesPlugin.md
- packages/website/docs/createQuerySuggestionsPlugin.md
- packages/website/docs/createRecentSearchesPlugin.md
When transforming plugin sources, you sometimes need to access the state to conditionally apply some logic. Providing the Autocomplete `state` to `transformSource` allow these use cases.
Example of Query Suggestions hidden when there's no query.
```ts
const querySuggestionsPlugin = createQuerySuggestionsPlugin({
searchClient,
indexName: 'instant_search_demo_query_suggestions',
transformSource({ source, state }) {
if (!state.query) {
return null;
}
return source;
},
});
```
> feat(plugins): provide `state` to `transformSource`

- examples/github-repositories-custom-plugin/createGitHubReposPlugin.tsx
- packages/autocomplete-theme-classic/src/theme.scss
This tweaks the styles so that the search box visually aligns on other elements. This applies to the loading indicator too, and optimizes for the largest possible clickable/tappable area on the submit and clear buttons.
<details><summary><strong>Desktop</strong></summary>
</details>
<details><summary><strong>Mobile</strong></summary>
</details>
On mobile, the submit icon has to be close to the left edge to align with the icons below. I didn't replicate this exact gap between the clear button and the right edge, because it looked weird. I've tried to find a gap that felt right instead. It looks a bit odd when looking at it on a computer screen, but feels smooth on a mobile device.
I've tried to simplify the `calc` statements as much as possible so they don't wrap and are easier to read. …
> feat(autocomplete-theme-classic): align search box properly

- packages/website/docusaurus.config.js
- packages/website/package.json
- yarn.lock
This updates the website to the latest Docusaurus version. This version fixes some broken link issues that we had.
> chore(website): update to Docusaurus 2.0.0-alpha.72

- .gitignore
- cypress/test-apps/js/package.json
- examples/github-repositories-custom-plugin/package.json
- examples/playground/package.json
- examples/query-suggestions-with-categories/package.json
- examples/query-suggestions-with-hits/package.json
- examples/query-suggestions-with-inline-categories/package.json
- examples/query-suggestions-with-recent-searches/package.json
- examples/query-suggestions/package.json
- examples/recently-viewed-items/package.json
- examples/starter/package.json
- yarn.lock
Parcel 1 keeps throwing random errors in monorepos. The [maintainer recommends upgrading to v2](https://github.com/parcel-bundler/parcel/issues/5943#issuecomment-799899064) right now, even though it's flagged as beta (but published on the `latest` npm tag).
This version seems to work as expected.
> chore(examples): update Parcel to v2

- README.md
- packages/website/docs/autocomplete-js.md
- packages/website/docs/createAlgoliaInsightsPlugin.md
- packages/website/docs/createAutocomplete.md
- packages/website/docs/createLocalStorageRecentSearchesPlugin.md
- packages/website/docs/createQuerySuggestionsPlugin.md
- packages/website/docs/createRecentSearchesPlugin.md
- packages/website/docs/getAlgoliaFacetHits-js.mdx
- packages/website/docs/getAlgoliaFacetHits.mdx
- packages/website/docs/getAlgoliaHits-js.mdx
- packages/website/docs/getAlgoliaHits.mdx
- packages/website/docs/getAlgoliaResults-js.mdx
- packages/website/docs/getAlgoliaResults.mdx
- packages/website/docs/getting-started.mdx
- packages/website/docs/parseAlgoliaHitHighlight.md
- packages/website/docs/parseAlgoliaHitReverseHighlight.md
- packages/website/docs/parseAlgoliaHitReverseSnippet.md
- packages/website/docs/parseAlgoliaHitSnippet.md
This adds documentation for users that don't use a package manager, but rely on `script` tags.
We need to document how to get the UMD export from the global object since the import is not so straightforward.
> docs: document `script` tag imports

- packages/website/package.json
- yarn.lock
This updates the DocSearch version on the website which fixes the noop <kbd>Enter</kbd> key on select.
> chore(website): update DocSearch to 3.0.0-alpha.35

- cypress/test-apps/js/app.tsx
- cypress/test-apps/js/categoriesPlugin.tsx
- cypress/test-apps/js/shortcutsPlugin.tsx
- examples/github-repositories-custom-plugin/createGitHubReposPlugin.tsx
- examples/playground/app.tsx
- examples/playground/categoriesPlugin.tsx
- examples/playground/shortcutsPlugin.tsx
- examples/query-suggestions-with-hits/app.tsx
- examples/query-suggestions-with-inline-categories/app.tsx
- examples/react-renderer/src/Autocomplete.tsx
- examples/recently-viewed-items/app.tsx
- packages/autocomplete-plugin-query-suggestions/src/getTemplates.tsx
- packages/autocomplete-plugin-recent-searches/src/getTemplates.tsx
- packages/autocomplete-theme-classic/src/theme.scss
- packages/website/docs/autocomplete-theme-classic.md
- packages/website/docs/getting-started.mdx
- packages/website/docs/sending-algolia-insights-events.md
- packages/website/docs/using-vue.md
- packages/website/src/components/productsPlugin.tsx
We use CSS grids to display items in columns, meaning the grid algorithm always tries to render content into columns. For this reason, we need to make sure the HTML structure is always the same. **This means you now always need to either wrap the item within `aa-ItemWrapper` OR `aa-ItemLink`.**
This PR moves the grid display on `aa-ItemWrapper` and `aa-ItemLink`, and updates the documentation, demos and plugins to reflect the change.
> fix(theme-classic): wrap item content when there's no link

- packages/autocomplete-plugin-query-suggestions/src/createQuerySuggestionsPlugin.ts
When using the tap-ahead pattern on Query Suggestions, it's common to insert a space after the suggestion so that users can keep typing without manually adding a space.
> feat(qs): append space to query on tap-ahead

- packages/website/package.json
- yarn.lock
DocSearch version `3.0.0-alpha.35` has a regression that throws when you start typing.
> chore(website): downgrade DocSearch to 3.0.0-alpha.34

- cypress/test-apps/js/app.tsx
- examples/playground/app.tsx
- examples/query-suggestions-with-hits/app.tsx
- examples/recently-viewed-items/app.tsx
- packages/autocomplete-theme-classic/src/theme.scss
- packages/website/docs/autocomplete-theme-classic.md
This removes the pointer cursor on the no result item content.
> fix(classic-theme): remove pointer cursor on no result item content

- packages/autocomplete-theme-classic/src/theme.scss
We had a bug preventing the panel to display at all in desktop Detached Mode. This PR fixes it.
We should have a dedicated demo for desktop Detached Mode, along with visual regression tests to avoid breaking the UI without us knowing.
> fix(classic-theme): fix modal display in desktop Detached Mode

- packages/autocomplete-js/src/types/AutocompleteOptions.ts
We documented the old default value for `detachedMediaQuery`.
> docs(js): update `detachedMediaQuery` default value

- packages/autocomplete-js/src/types/AutocompleteComponents.ts
- packages/website/docs/autocomplete-js.md
The TSDoc description for the highlight components was missing.
> docs(js): add TSDoc for highlight components

- packages/autocomplete-js/src/__tests__/panelPlacement.test.ts
- packages/autocomplete-js/src/__tests__/positioning.test.ts
- packages/autocomplete-js/src/getPanelPlacementStyle.ts
Close #535 
The autocomplete container's parent element becomes `offsetParent` when there is a css declaration `position:relative`, where `offsetTop` is calculated relative to the parent element and not the actual position of the container in the page.
> fix(js): compute panel top position with `getBoundingClientRect`

- examples/github-repositories-custom-plugin/package.json
- examples/multiple-datasets-with-headers/package.json
- examples/playground/package.json
- examples/query-suggestions-with-categories/package.json
- examples/query-suggestions-with-hits/package.json
- examples/query-suggestions-with-inline-categories/package.json
- examples/query-suggestions-with-recent-searches-and-categories/package.json
- examples/query-suggestions-with-recent-searches/package.json
- examples/query-suggestions/package.json
- examples/recently-viewed-items/package.json
- examples/starter-algolia/package.json
- examples/starter/package.json
- examples/voice-search/package.json
**Summary**
Updates parcel 2 build command.
The `main` prop overrides the default `build` location (which is `./dist`)
[`main` usage](https://github.com/parcel-bundler/parcel/discussions/3377#discussioncomment-15960)
[parcel v2 `build`](https://v2.parceljs.org/features/cli/#parcel-build-%3Centries%3E)
> fix(examples): update build command

- packages/autocomplete-js/src/requesters/__tests__/getAlgoliaResults.test.ts
- packages/autocomplete-preset-algolia/src/requester/__tests__/getAlgoliaResults.test.ts
This adds unit tests for `getAlgoliaResults` in `autocomplete-js` and refactors the ones in `autocomplet-preset-algolia`.
> test: better test getAlgoliaResults

- cypress/test-apps/js/app.tsx
- examples/query-suggestions-with-hits/app.tsx
- examples/react-renderer/src/Autocomplete.tsx
- examples/recently-viewed-items/app.tsx
- examples/starter-algolia/app.tsx
- examples/voice-search/app.tsx
- packages/autocomplete-core/src/getAutocompleteSetters.ts
There were examples and tests still using the old API. This fixes it.
> fix: update examples and tests with Requester API

- packages/autocomplete-theme-classic/src/theme.scss
This PR fixes small visual issues in the theme:
- Vertical alignment of items
- Bottom gradient cut on non-Webkit browsers (not supporting the scrollbar customization)
- Bottom gradient not rounded on Safari
> fix(theme-classic): various fixes

- packages/autocomplete-js/src/types/AutocompleteOptions.ts
**Summary**
Expose `GetSources` type in autocomplete-js, which can be useful when extracting the function from the Autocomplete instance.
Used in the `panel-placement` example: https://github.com/algolia/autocomplete/pull/549
> feat(js): expose `GetSources` type

- cypress/test-apps/js/package.json
- examples/instantsearch/package.json
- examples/multiple-datasets-with-headers/package.json
- examples/panel-placement/package.json
- examples/playground/package.json
- examples/preview-panel-in-modal/package.json
- examples/query-suggestions-with-categories/package.json
- examples/query-suggestions-with-hits/package.json
- examples/query-suggestions-with-inline-categories/package.json
- examples/query-suggestions-with-recent-searches-and-categories/package.json
- examples/query-suggestions-with-recent-searches/package.json
- examples/query-suggestions/package.json
- examples/react-renderer/package.json
- examples/recently-viewed-items/package.json
- examples/starter-algolia/package.json
- examples/voice-search/package.json
- package.json
- packages/autocomplete-core/package.json
- packages/autocomplete-js/package.json
- packages/autocomplete-plugin-query-suggestions/package.json
- packages/autocomplete-plugin-recent-searches/package.json
- packages/autocomplete-preset-algolia/package.json
- yarn.lock
This updates the search client dependencies to 4.9.1 which bring better support for `facetQuery` typings.
> chore(deps): update algoliasearch to 4.9.1

- packages/autocomplete-js/src/__tests__/detached.test.ts
- packages/autocomplete-js/src/autocomplete.ts
- packages/autocomplete-js/src/createAutocompleteDom.ts
- packages/autocomplete-js/src/elements/Input.ts
This synchronizes the internal open state with the detached overlay open state.
It was a missing behavior that caused some trouble to users, unable to trigger an action (other than a link) after a selection on detached mode.
We're now syncing the detached open state with the internal `isOpen` state. This means that `shouldPanelOpen` always return `true` on detached mode now. Otherwise, the detached overlay wouldn't be able to stay open under user conditions.
- Closes #547
> feat(js): sync detached mode open state

- packages/autocomplete-core/src/types/AutocompleteOptions.ts
- packages/autocomplete-core/src/types/AutocompletePlugin.ts
- packages/autocomplete-core/src/types/AutocompleteSetters.ts
- packages/autocomplete-core/src/types/AutocompleteSource.ts
- packages/autocomplete-js/src/types/AutocompleteOptions.ts
- packages/autocomplete-js/src/types/AutocompletePlugin.ts
- packages/autocomplete-js/src/types/AutocompleteSource.ts
- packages/autocomplete-js/src/types/AutocompleteState.ts
- packages/autocomplete-plugin-algolia-insights/src/createAlgoliaInsightsPlugin.ts
- packages/autocomplete-plugin-query-suggestions/src/createQuerySuggestionsPlugin.ts
- packages/autocomplete-plugin-recent-searches/src/createLocalStorageRecentSearchesPlugin.ts
- packages/autocomplete-plugin-recent-searches/src/createRecentSearchesPlugin.ts
- packages/autocomplete-preset-algolia/src/requester/createRequester.ts
This updates all the documentation links from our TSDoc to the Algolia documentation website.
(Links won't work until we deploy the new documentation content.)
> docs(ts): update TSDoc links to official documentation

- bundlesize.config.json
- packages/autocomplete-core/src/utils/__tests__/mapToAlgoliaResponse.test.ts
- packages/autocomplete-core/src/utils/mapToAlgoliaResponse.ts
In #540, we introduced the Requester API to batch Algolia queries, but we [left out Insights plugin support](https://github.com/algolia/autocomplete/blob/c62f1d2757c5824c5a2f456c20cf55ca3d962cdb/packages/autocomplete-preset-algolia/src/search/getAlgoliaHits.ts#L18-L19). These metadata fields are required for the Insights plugin to send events to the API.
This PR brings support for the Insights plugin from requesters by adding back the necessary metadata in the hits returned by the Algolia API.
- https://github.com/algolia/autocomplete/discussions/559#discussioncomment-686775
> fix(core): support Insights in requesters

- packages/website/_redirects
- packages/website/package.json
This prepares the redirect rules for the Autocomplete website to redirect to the Algolia docs.
**We need to merge this PR right after release.**
> chore(website): add redirect rules to Algolia website

- .eslintignore
The `.docusaurus` folder doesn't exist anymore so we don't need to ignore it in our ESLint config.
> chore(eslint): remove Docusaurus files from config

- .prettierignore
- .prettierrc
- examples/react-renderer/tsconfig.json
This sets Prettier's `endOfLine` configuration to its default which is set to `"lf"`.
It also updates the files that Prettier should ignore.
See: https://prettier.io/docs/en/options.html#end-of-line
> chore(prettier): update config

- packages/autocomplete-js/src/components/Highlight.ts
- packages/autocomplete-js/src/components/ReverseHighlight.ts
- packages/autocomplete-js/src/components/ReverseSnippet.ts
- packages/autocomplete-js/src/components/Snippet.ts
This syntax is more conventional when using Fragments and Vue 3 doesn't support spreading children with Fragments.
- Closes #574
> fix(js): pass children as array in highlight components

- packages/autocomplete-js/src/__tests__/autocomplete.test.ts
- packages/autocomplete-js/src/render.tsx
**Summary**
On an empty query, nothing is rendered when `openOnFocus` is `true` and a `noResults` template is provided.
**[live reproduction](https://codesandbox.io/s/serene-shadow-26bhx?file=/app.tsx)**:
- Focus input: nothing is rendered.
- Type something: `noResults` template is rendered.
**Result**
The `noResults` template is rendered on an empty query with `openOnFocus: true`
> fix(js): render `noResults` template when `openOnFocus` is `true`

- examples/instantsearch/package.json
- examples/instantsearch/src/instantsearch.ts
- yarn.lock
In algolia/instantsearch.js#4750 we introduced the `getUiState` API which allows to retrieve the current category more easily.
> docs(examples): use InstantSearch's `getUiState`

- packages/autocomplete-js/src/__tests__/panelPlacement.test.ts
- packages/autocomplete-js/src/__tests__/positioning.test.ts
- packages/autocomplete-js/src/getPanelPlacementStyle.ts
**Summary**
Since https://github.com/algolia/autocomplete/pull/536, the panel wasn't well positioned after scrolling.
**Results**
Panel is positioned below the input, still fixes https://github.com/algolia/autocomplete/issues/535.
Closes https://github.com/algolia/autocomplete/issues/591
> fix(js): fix panel placement after scrolling

- cypress/test-apps/js/categoriesPlugin.tsx
- examples/instantsearch/src/autocomplete.tsx
- examples/multiple-datasets-with-headers/app.tsx
- examples/multiple-datasets-with-headers/categoriesPlugin.tsx
- examples/playground/categoriesPlugin.tsx
- examples/preview-panel-in-modal/app.tsx
- examples/query-suggestions-with-recent-searches/app.tsx
- examples/recently-viewed-items/recentlyViewedItemsPlugin.tsx
- packages/autocomplete-js/src/__tests__/render.test.ts
- packages/autocomplete-js/src/render.tsx
**Summary**
When having multi-sources, sections without results and `noResults` template were still rendering their `header` and/or `footer` template, which required some extra logic for the user.
**Result**
Sections without results and `noResults` template are not rendered anymore.
> fix(js): do not render empty sections

- packages/autocomplete-js/src/getPanelPlacementStyle.ts
Some browsers have specificities to retrieve the document scroll position. This solution should support all browsers.
- https://github.com/algolia/autocomplete/issues/591#issuecomment-847972545
- https://stackoverflow.com/a/28633515/9940315
> fix(js): support panel scroll top position in all browsers

- packages/autocomplete-js/src/__tests__/render.test.ts
- packages/autocomplete-js/src/render.tsx
- packages/autocomplete-js/src/types/AutocompleteRender.ts
This forwards the scoped API (setters and `refresh`) to the `render` param to allow complex UIs.
This is useful when you want to interact with the Autocomplete lifecycle from the global `render` hook, with a preview panel for instance.
```tsx
autocomplete({
// ...
render({ elements, setQuery, refresh }, root) {
render(
<PreviewPanel
elements={elements}
onItemSelect={(item) => {
setQuery(item.query);
refresh();
}}
/>,
root
);
},
});
```
> feat(js): provide setters and refresh to `render` API

- packages/autocomplete-js/src/__tests__/autocomplete.test.ts
- packages/autocomplete-js/src/__tests__/detached.test.ts
- packages/autocomplete-js/src/__tests__/detachedMediaQuery.test.ts
- packages/autocomplete-js/src/__tests__/translations.test.ts
- packages/autocomplete-js/src/autocomplete.ts
- scripts/jest/setupTests.ts
- test/utils/createMatchMedia.ts
- test/utils/index.ts
**Summary**
`addEventListener` on media queries isn't supported for iOS <= 13.6, which causes Autocomplete to crash the application. We now provide a fallback solution to the deprecated method `addListener`.
**Result**
Autocomplete no longer crashes on iOS <= 13.6
**Video**
Following the steps of https://github.com/algolia/autocomplete/issues/597, the device is an iPhone 11 running on iOS 13.6.
- At the beginning, we can see the sandbox of the issue (without the workaround) throwing an error. [sandbox](https://codesandbox.io/s/blazing-star-ke0de?file=/index.html)
- The second sandbox is the one from this commit, with the code from `app.tsx` (from the one above) copy pasted. [sandbox](https://codesandbox.io/s/algoliaautocomplete-example-starter-algolia-forked-jxl1l?file=/app.tsx) …
> fix(js): provide fallback method for `addEventListener` on media queries

- packages/autocomplete-core/src/__tests__/getSources.test.ts
- packages/autocomplete-core/src/onInput.ts
- packages/autocomplete-core/src/resolve.ts
When users don't return anything from `getItems`, they get an unhelpful runtime error:
```txt
"Cannot read property 'execute' of undefined"
```
**Reproduction link:** https://codesandbox.io/s/wizardly-rgb-i69uy (try typing, then see error)
This is because the Requester API determines whether the returned value is a requester description by looking for an `execute` property on them. If there's no return statement in `getItems`, the value is `undefined` and the runtime throws.
This is fine in production, but not too helpful during development, especially for non-TypeScript users who won't get a type error in their editor. This PR therefore adds an invariant to provide a more helpful development error.
The test uses a spy on `onInput` because at the level where we're testing, there's no way …
> fix(core): trigger invariant when user doesn't return anything from `getItems`

- bundlesize.config.json
- packages/autocomplete-core/src/__tests__/getInputProps.test.ts
- packages/autocomplete-core/src/onKeyDown.ts
- packages/autocomplete-core/src/stateReducer.ts
- packages/autocomplete-core/src/types/AutocompleteStore.ts
**Summary**
With the input focused, pressing <kbd>↓</kbd> or <kbd>↑</kbd> should open the panel if it was previously closed.
**Result**
With `openOnFocus: true` or a query, and the input focused:
- Pressing <kbd>↓</kbd> will open the panel with the input focused.
- Pressing <kbd>↑</kbd> will open the panel with the last element of the list focused.
Reference: [w3c aria practices](https://w3c.github.io/aria-practices/#combobox-keyboard-interaction)
Closes https://github.com/algolia/autocomplete/issues/584
> fix(core): open closed panel on `ArrowDown` and `ArrowUp`

- bundlesize.config.json
- packages/autocomplete-core/src/__tests__/completion.test.ts
- packages/autocomplete-core/src/getCompletion.ts
- packages/autocomplete-core/src/utils/getNextActiveItemId.ts
**Summary**
With an empty `collections`, `itemInputValue` was undefined which was throwing an error when destructuring it.
**Result**
- We now check that `itemInputValue` exists before returning it, otherwise, we return `null`.
- The `activeItemId` returned was `-1`, we now return `null` if there's no items in the collections.
> fix(completion): prevent error when getting `activeItem` with an empty collection

- packages/autocomplete-js/src/getDefaultOptions.ts
- packages/autocomplete-js/src/render.tsx
Thanks @ethanresnick for pointing this out!
closes #627
It looks like the panelLayout class wasn't used, because two class names needed to be added. This isn't used in any other place, so any panel layout is also a scrollable panel as far as I can tell :)
> fix(js): use user-provided panelLayout class

- packages/autocomplete-core/src/__tests__/getSources.test.ts
- packages/autocomplete-core/src/resolve.ts
- packages/autocomplete-core/src/utils/__tests__/getNormalizedSources.test.ts
- packages/autocomplete-core/src/utils/getNormalizedSources.ts
- packages/autocomplete-shared/src/__tests__/decycle.test.ts
- packages/autocomplete-shared/src/__tests__/invariant.test.ts
- packages/autocomplete-shared/src/decycle.ts
- packages/autocomplete-shared/src/index.ts
- packages/autocomplete-shared/src/invariant.ts
This introduces a `decycle` utility to replace cyclic references in objects before serializing them with `JSON.stringify`.
It uses a slightly modified version of Crockford's [cycle.js](https://github.com/douglascrockford/JSON-js/blob/master/cycle.js), [which MDN recommends](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#issue_with_json.stringify_when_serializing_circular_references). This works better than `JSON.stringify`'s `replacer`, because the latter walks every node in the object, making it difficult to preserve non-circular structures like the following:
```js
const a = { a: 1 };
const obj = [a, a]; // JSON.strinigfy can handle this, we don't want to end up with `[{ "a": 1 }, "[Circular]"]`
```
Whenever a circular reference is met, …
> fix: decycle potentially cyclic structures before serializing

- bundlesize.config.json
- packages/autocomplete-theme-classic/package.json
- postcss.config.mjs
**Summary**
Users were not able to build `create-react-app` applications when using the autocomplete theme due to a postcss bug with the minified version. See https://github.com/algolia/autocomplete/issues/626 for more details.
We now provide a non-minified version of the theme as a workaround to prevent this issue.
**Result**
- The main file is still the minified version, but is now called `theme.min.css`
- The non-minified version is available at `@algolia/autocomplete-theme-classic/dist/theme.css`
Closes https://github.com/algolia/autocomplete/issues/626
> feat(theme): provide non-minified theme

- jest.config.js
**This maps imports of Autocomplete libraries to their source code (instead of the build) during tests.** This creates better DX as we no longer need to rebuild updated modules when we need to test other modules that depend on them.
> build(jest): map modules to sources during tests

- examples/twitter-compose-with-typeahead/src/App.tsx
- examples/twitter-compose-with-typeahead/src/Autocomplete.tsx
- examples/twitter-compose-with-typeahead/src/utils/getActiveToken.ts
- examples/twitter-compose-with-typeahead/src/utils/isValidTwitterUsername.ts
This refactors a few aspects of the Twitter example to reflect exactly the code from the [documentation guide](https://github.com/algolia/doc/pull/6240).
- Moved `defaultActiveItemId` inside the component
- Updated the name of the argument passed to `getActiveToken`
- Simplify Twitter username validation predicate with a better regular expression
> refactor(examples): simplify code

- .circleci/config.yml
**Summary**
Fixes Circle CI docker image issue
See https://circleci.com/developer/images/image/cimg/node for more informations
TLDR: `This image is designed to supercede the legacy CircleCI Node.js image, circleci/node.`
> fix(ci): update docker image

- lerna.json
The [`useWorkspaces`](https://github.com/lerna/lerna/tree/main/commands/bootstrap#--use-workspaces) option enables better integration with Yarn Workspaces.
It is [required for Renovate](https://github.com/renovatebot/renovate/issues/7438#issuecomment-739755253) to use the `yarn` command instead of `lerna`.
- algolia/docsearch#1158
- algolia/react-instantsearch#3189
> chore(lerna): add `useWorkspaces` option

- lerna.json
With the `useWorkspaces` option, Lerna relies on Yarn Workspaces defined in the root `package.json`.
> chore(lerna): rely on Yarn Workspaces

- examples/github-notification-filters/app.tsx
- examples/github-notification-filters/components/PostfixItem.tsx
- examples/github-notification-filters/items.ts
- examples/github-notification-filters/package.json
- examples/github-notification-filters/searchClient.ts
- examples/github-notification-filters/style.css
- examples/github-notification-filters/types/AutocompleteItem.ts
- examples/github-notification-filters/types/Contributor.ts
- examples/github-notification-filters/types/NotificationFilter.ts
- examples/github-notification-filters/types/Repository.ts
- examples/github-notification-filters/types/index.ts
This swaps the static sources for repositories, authors and organizations with Algolia indices. This allows us to leverage Algolia features (full-text search, highlighting, custom ranking, search for facet values, etc.).
When a tag is selected, it's removed from the available filters to avoid adding the same tag twice and polluting the results.
https://user-images.githubusercontent.com/5370675/141218784-f8a45c3c-3b3e-4d9b-918b-4688258b373a.mov
The indices are static extracts from the GitHub public API, indexed in Algolia. They contain a list of public repos from Algolia and CodeSandbox, along with public members of both organizations.
[sandbox](http://codesandbox.io/s/github/algolia/autocomplete/tree/docs/github-filters-algolia/examples/github-notification-filters)
> docs(example): set up GitHub filters example with Algolia

- README.md
This PR adds a mention in the README, asking developers to use `@algolia/instantsearch-js` instead.
Closes FX-548.
> chore: add deprecation notice with redirection to new package

- packages/autocomplete-core/src/createStore.ts
- packages/autocomplete-core/src/getPropGetters.ts
- packages/autocomplete-core/src/onInput.ts
- packages/autocomplete-core/src/onKeyDown.ts
- packages/autocomplete-core/src/types/AutocompleteStore.ts
This is a proposed patch on top of #829.
See https://github.com/algolia/autocomplete/pull/829#pullrequestreview-822667289.
I did it very quickly so we can rename things later.
> fix(concurrency): ensure panel stays closed after blur (patch)

- bundlesize.config.json
- packages/autocomplete-core/src/__tests__/concurrency.test.ts
- packages/autocomplete-core/src/__tests__/getEnvironmentProps.test.ts
- packages/autocomplete-core/src/__tests__/getInputProps.test.ts
- packages/autocomplete-core/src/__tests__/getSources.test.ts
- packages/autocomplete-core/src/createStore.ts
- packages/autocomplete-core/src/getPropGetters.ts
- packages/autocomplete-core/src/onInput.ts
- packages/autocomplete-core/src/onKeyDown.ts
- packages/autocomplete-core/src/types/AutocompleteStore.ts
- packages/autocomplete-core/src/utils/__tests__/createConcurrentSafePromise.test.ts
- packages/autocomplete-core/src/utils/createConcurrentSafePromise.ts
This fixes a concurrency issue with closing the panel by running an additional tracked promise without triggering a search.
When a user types a query that triggers network requests (for example, to Algolia), these requests could sometimes take longer to resolve (e.g., the service is slow, the network is slow). In the meantime, the user could decide to manually close the panel. However, a late resolving request could reopen the panel.
This doesn't make sense from a functional perspective: if you've purposefully closed the panel, it should be considered a cancellation.
The issue comes from late promises in `onInput` performing asynchronous state updates that cancel previous ones. This is a similar problem to #654.
Since we can't avoid asynchronous and potentially late state updates, we can …
> fix(concurrency): ensure panel stays closed after blur
